spring:
  profiles:
    active:
    - dev
---
server:
  port: 8005
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      detaultZone: http://eureka-dev.com:7001/eureka

---
server:
  port: 8006
spring:
  profiles: test
  application:
    name: microservicecloud-config-client

eureka:
  client:
    service-url:
      detaultZone: http://eureka-test.com:7001/eureka